<?php

declare(strict_types=1);

namespace App\Support;

use InvalidArgumentException;

/**
 * Derives a whole interface palette — light and dark — from the two hex colours
 * a tenant picked.
 *
 * The problem with letting a customer choose a colour is that most colours are
 * unreadable somewhere. A pale yellow is invisible on white, a navy is
 * invisible on a dark surface, and a palette generated by rotating the hue and
 * calling it done ships an interface that fails WCAG for the tenant who chose
 * it and for nobody else, which is exactly the failure nobody tests.
 *
 * So every colour this class emits is lifted until it clears the ratio the pair
 * it takes part in needs: 4.5:1 where text is read, 3:1 for borders and large
 * UI. Lifting moves lightness only, and only within a window around the colour
 * the tenant chose, because a "brand blue" dragged across half the lightness
 * range is no longer their blue. When the window is not enough — a near-white
 * accent asked to carry white text — the token falls back to the neutral ramp
 * instead of shipping a colour that fails. A grey the tenant did not choose is
 * a disappointment; unreadable text is a defect.
 *
 * Ratios are measured on the colour a browser actually paints: OKLCH covers
 * more than sRGB, so each candidate is converted and clipped to the display
 * gamut first, and the ratio is read from what survived the clip.
 */
final class BrandPalette
{
    /**
     * The pairs a reader ever actually looks at, and the ratio each one owes:
     * [foreground token, background token, minimum ratio].
     *
     * This list is what "the palette is accessible" means here. A token pair
     * missing from it is a pair nothing checks, so anything the interface puts
     * on top of anything else belongs in it.
     *
     * @var list<array{string, string, float}>
     */
    public const array PAIRS = [
        ['foreground', 'surface', 4.5],
        ['foreground', 'surface-raised', 4.5],
        ['foreground', 'surface-sunken', 4.5],
        ['foreground-muted', 'surface', 4.5],
        ['foreground-muted', 'surface-raised', 4.5],
        ['border', 'surface', 3.0],
        ['border-strong', 'surface', 3.0],
        ['on-primary', 'primary', 4.5],
        ['on-primary', 'primary-hover', 4.5],
        ['on-primary', 'primary-active', 4.5],
        ['primary', 'surface', 3.0],
        ['on-accent', 'accent', 4.5],
        ['on-accent', 'accent-hover', 4.5],
        ['on-accent', 'accent-active', 4.5],
        ['accent', 'surface', 3.0],
        ['on-success', 'success', 4.5],
        ['success', 'surface', 3.0],
        ['on-warning', 'warning', 4.5],
        ['warning', 'surface', 3.0],
        ['on-danger', 'danger', 4.5],
        ['danger', 'surface', 3.0],
    ];

    /** The palette a tenant that never picked colours gets. */
    public const string DEFAULT_PRIMARY = '#3366FF';

    public const string DEFAULT_ACCENT = '#FF9900';

    /**
     * How far lightness may travel from the colour the tenant chose before the
     * result stops being their colour.
     */
    private const float WINDOW = 0.35;

    /** The lightness granularity the search walks. */
    private const float STEP = 0.005;

    /**
     * Ratios are asserted against the rounded token string, so the search aims
     * slightly above the bar to leave rounding no room to cross back under it.
     */
    private const float MARGIN = 0.02;

    /** @var array{float, float, float} */
    private const array NEUTRAL = [0.0, 0.0, 0.0];

    /**
     * The derived palette, as CSS `oklch()` strings keyed by token name.
     *
     * @return array{light: array<string, string>, dark: array<string, string>}
     */
    public static function from(string $primaryHex, string $accentHex): array
    {
        $primary = self::toOklch($primaryHex);
        $accent = self::toOklch($accentHex);

        return [
            'light' => self::mode($primary, $accent, light: true),
            'dark' => self::mode($primary, $accent, light: false),
        ];
    }

    /** The measured WCAG contrast ratio between two emitted tokens. */
    public static function contrast(string $foreground, string $background): float
    {
        return self::ratio(self::parse($foreground), self::parse($background));
    }

    /** The perceptual lightness of a hex colour, on OKLCH's 0..1 scale. */
    public static function lightness(string $hex): float
    {
        return self::toOklch($hex)[0];
    }

    /**
     * @param  array{float, float, float}  $primary
     * @param  array{float, float, float}  $accent
     * @return array<string, string>
     */
    private static function mode(array $primary, array $accent, bool $light): array
    {
        $hue = $primary[2];

        $surface = [$light ? 0.99 : 0.16, 0.004, $hue];
        $raised = [$light ? 1.0 : 0.205, 0.004, $hue];
        $sunken = [$light ? 0.965 : 0.12, 0.006, $hue];

        // One foreground carries every brand background, so each of those
        // backgrounds is lifted until this exact colour reads on it.
        $onBrand = [$light ? 1.0 : 0.14, 0.0, $hue];

        $readable = [[$surface, 3.0], [$onBrand, 4.5]];

        $tokens = [
            'surface' => $surface,
            'surface-raised' => $raised,
            'surface-sunken' => $sunken,
            'foreground' => self::liftToContrast(
                [$light ? 0.22 : 0.96, min($primary[1], 0.02), $hue],
                [[$surface, 4.5], [$raised, 4.5], [$sunken, 4.5]],
            ),
            'foreground-muted' => self::liftToContrast(
                [$light ? 0.5 : 0.72, min($primary[1], 0.02), $hue],
                [[$surface, 4.5], [$raised, 4.5]],
            ),
            'border' => self::liftToContrast([$light ? 0.85 : 0.32, 0.01, $hue], [[$surface, 3.0]]),
            'border-strong' => self::liftToContrast([$light ? 0.7 : 0.45, 0.02, $hue], [[$surface, 3.0]]),
            'on-primary' => $onBrand,
            'on-accent' => $onBrand,
            'on-success' => $onBrand,
            'on-warning' => $onBrand,
            'on-danger' => $onBrand,
        ];

        $seeds = [
            'primary' => $primary,
            'accent' => $accent,
            'success' => [$light ? 0.55 : 0.78, 0.15, 145.0],
            'warning' => [$light ? 0.55 : 0.78, 0.15, 75.0],
            'danger' => [$light ? 0.55 : 0.78, 0.15, 25.0],
        ];

        foreach ($seeds as $name => $seed) {
            $tokens[$name] = self::liftToContrast($seed, $readable);
        }

        // Hover and active are derived from the lifted base rather than from
        // the seed, so a family that fell back to neutral stays one family.
        foreach (['primary', 'accent'] as $name) {
            $base = $tokens[$name];
            $direction = $light ? -1.0 : 1.0;

            $tokens[$name.'-hover'] = self::liftToContrast([$base[0] + ($direction * 0.05), $base[1], $base[2]], $readable);
            $tokens[$name.'-active'] = self::liftToContrast([$base[0] + ($direction * 0.1), $base[1], $base[2]], $readable);
        }

        return array_map(self::format(...), $tokens);
    }

    /**
     * Move lightness until the colour clears every ratio it owes, staying as
     * close to the colour it was given as the constraints allow.
     *
     * @param  array{float, float, float}  $color
     * @param  list<array{array{float, float, float}, float}>  $constraints
     * @return array{float, float, float}
     */
    private static function liftToContrast(array $color, array $constraints): array
    {
        $lifted = self::firstMeeting(self::candidates($color, self::WINDOW), $constraints)
            ?? self::firstMeeting(self::candidates([$color[0], 0.0, 0.0], 1.0), $constraints);

        return $lifted ?? self::NEUTRAL;
    }

    /**
     * Lightnesses to try, nearest to the given colour first, so the winner is
     * the smallest departure from it that works.
     *
     * @param  array{float, float, float}  $color
     * @return list<array{float, float, float}>
     */
    private static function candidates(array $color, float $window): array
    {
        $color = [self::clip($color[0]), $color[1], $color[2]];

        $candidates = [$color];

        for ($delta = self::STEP; $delta <= $window; $delta += self::STEP) {
            foreach ([$color[0] - $delta, $color[0] + $delta] as $lightness) {
                if ($lightness >= 0.0 && $lightness <= 1.0) {
                    $candidates[] = [$lightness, $color[1], $color[2]];
                }
            }
        }

        return $candidates;
    }

    /**
     * @param  list<array{float, float, float}>  $candidates
     * @param  list<array{array{float, float, float}, float}>  $constraints
     * @return array{float, float, float}|null
     */
    private static function firstMeeting(array $candidates, array $constraints): ?array
    {
        foreach ($candidates as $candidate) {
            foreach ($constraints as [$background, $minimum]) {
                if (self::ratio($candidate, $background) < $minimum + self::MARGIN) {
                    continue 2;
                }
            }

            return $candidate;
        }

        return null;
    }

    /**
     * @param  array{float, float, float}  $foreground
     * @param  array{float, float, float}  $background
     */
    private static function ratio(array $foreground, array $background): float
    {
        $first = self::luminance($foreground);
        $second = self::luminance($background);

        return (max($first, $second) + 0.05) / (min($first, $second) + 0.05);
    }

    /**
     * WCAG relative luminance of the colour a display can actually show: the
     * out-of-gamut part is clipped first, because a ratio measured on a colour
     * no screen can paint is a ratio nobody sees.
     *
     * @param  array{float, float, float}  $color
     */
    private static function luminance(array $color): float
    {
        [$red, $green, $blue] = self::toLinearRgb($color);

        return (0.2126 * $red) + (0.7152 * $green) + (0.0722 * $blue);
    }

    /**
     * @param  array{float, float, float}  $color
     * @return array{float, float, float}
     */
    private static function toLinearRgb(array $color): array
    {
        [$lightness, $chroma, $hue] = $color;

        $radians = deg2rad($hue);
        $a = $chroma * cos($radians);
        $b = $chroma * sin($radians);

        $long = ($lightness + (0.3963377774 * $a) + (0.2158037573 * $b)) ** 3;
        $medium = ($lightness - (0.1055613458 * $a) - (0.0638541728 * $b)) ** 3;
        $short = ($lightness - (0.0894841775 * $a) - (1.2914855480 * $b)) ** 3;

        return [
            self::clip((4.0767416621 * $long) - (3.3077115913 * $medium) + (0.2309699292 * $short)),
            self::clip((-1.2684380046 * $long) + (2.6097574011 * $medium) - (0.3413193965 * $short)),
            self::clip((-0.0041960863 * $long) - (0.7034186147 * $medium) + (1.7076147010 * $short)),
        ];
    }

    private static function clip(float $channel): float
    {
        return max(0.0, min(1.0, $channel));
    }

    /**
     * @return array{float, float, float}
     */
    private static function toOklch(string $hex): array
    {
        if (preg_match('/^#([0-9a-f]{6})$/i', $hex, $matches) !== 1) {
            throw new InvalidArgumentException(sprintf('%s is not a six-digit hex colour.', $hex));
        }

        /** @var list<int> $channels */
        $channels = array_map(hexdec(...), mb_str_split($matches[1], 2));

        [$red, $green, $blue] = array_map(
            static fn (int $channel): float => self::toLinear($channel / 255),
            $channels,
        );

        $long = ((0.4122214708 * $red) + (0.5363325363 * $green) + (0.0514459929 * $blue)) ** (1 / 3);
        $medium = ((0.2119034982 * $red) + (0.6806995451 * $green) + (0.1073969566 * $blue)) ** (1 / 3);
        $short = ((0.0883024619 * $red) + (0.2817188376 * $green) + (0.6299787005 * $blue)) ** (1 / 3);

        $lightness = (0.2104542553 * $long) + (0.7936177850 * $medium) - (0.0040720468 * $short);
        $a = (1.9779984951 * $long) - (2.4285922050 * $medium) + (0.4505937099 * $short);
        $b = (0.0259040371 * $long) + (0.7827717662 * $medium) - (0.8086757660 * $short);

        return [$lightness, hypot($a, $b), fmod(rad2deg(atan2($b, $a)) + 360.0, 360.0)];
    }

    private static function toLinear(float $channel): float
    {
        return $channel <= 0.04045 ? $channel / 12.92 : (($channel + 0.055) / 1.055) ** 2.4;
    }

    /**
     * @return array{float, float, float}
     */
    private static function parse(string $token): array
    {
        if (preg_match('/^oklch\((\d*\.?\d+) (\d*\.?\d+) (\d*\.?\d+)\)$/', $token, $matches) !== 1) {
            throw new InvalidArgumentException(sprintf('%s is not an oklch() colour.', $token));
        }

        return [(float) $matches[1], (float) $matches[2], (float) $matches[3]];
    }

    /**
     * @param  array{float, float, float}  $color
     */
    private static function format(array $color): string
    {
        return sprintf('oklch(%.4f %.4f %.2f)', $color[0], $color[1], $color[2]);
    }
}
